### ISSUE TITLE
Issue with RTIMU dependency

### ISSUE THREAD

**Issue by tolnai** [cgomesu/rpi-sensehat-mqtt#8]
I had to re-install my rpi, and started from a fresh scratch installation. I couldn't install dependencies anymore the "normal" way, so I set up a venv and activated it. Dependencies then got installed, but when I try to run the app, now I get `No module named 'RTIMU'` error. `python3-rtimulib` was already installed, but then I guess that conflicts with the venv some how. When I try to `pip3 install rtimulib` from the venv, then I get an error: `cc1plus: fatal error: ../../RTIMULib/IMUDrivers/RTHumidity.cpp: No such file or directory`. Not sure how to proceed, can you perhaps advise? Thanks!

**Comment by tolnai** [comment]
So, it's working if I use this:
```
pip3 install --upgrade pip --break-system-packages
pip3 install -r requirements.txt  --break-system-packages
```
But I was wondering if this is what should be added to the docs, or is there a way to use venv.

**Comment by tolnai** [comment]
Btw, I documented my own setup guide here: [](https://github.com/tolnai/matrix/blob/main/sensehat.md)

**Comment by cgomesu** [comment]
thanks for the heads up. yep. pip won't install packages if there's another package manager taking care of them, as it is the case in most OSes (e.g., apt for Debian). there are a few solutions though. you can install them via your OS pkg manager, use a virtual env or like you said, let pip handle the global install by using the `--break-system-packages` flag.

> But I was wondering if this is what should be added to the docs, or is there a way to use venv.

it should. if you don't mind, please feel free to make the changes and push them to this repo via a PR.

> Btw, I documented my own setup guide here: 

where? think you forgot to post the link.

**Comment by tolnai** [comment]
Sorry, link was badly formatted, [https://github.com/tolnai/matrix/blob/main/sensehat.md](https://github.com/tolnai/matrix/blob/main/sensehat.md).

I couldn't figure out how to make that lib work with venv, so I just appended that flag to 2 commands and that's it.

**Comment by cgomesu** [comment]
> I couldn't figure out how to make that lib work with venv, so I just appended that flag to 2 commands and that's it.

if you want to learn about the details: https://peps.python.org/pep-0668/

> Sorry, link was badly formatted, https://github.com/tolnai/matrix/blob/main/sensehat.md.

404ed... :disappointed:
